
services:
  ros2_compose:
    container_name: r2
    build:
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
    network_mode: host
    privileged: true
    user: ${LOCAL_USER_ID}:${LOCAL_GROUP_ID}
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1  
    tty: true
    command: [
        "tail -f /dev/null",
      ]
